name: openear
description: "A Flutter project for voice and file-based note upload."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Text-to-Speech
  flutter_tts: ^4.2.3

  # Speech-to-Text
  speech_to_text: ^7.3.0

  # File picking
  file_picker: ^8.3.7

  # Archive (for DOCX extraction)
  archive: ^3.6.1

  # Permissions handler
  permission_handler: ^12.0.1 

  # Path provider
  path_provider: ^2.0.15
  
  # PDF Text Extraction
  syncfusion_flutter_pdf: ^27.1.58

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/OpenEar_logo.jpg
